// Generated by https://quicktype.io

export interface GetEmployeesResponse {
  success: boolean;
  data:    Data;
}

export interface Data {
  employees: Employee[];
}

export interface Employee {
  id:        number;
  name:      string;
  last_name: string;
  birthday:  number;
}

export type RenderedEmployee = Omit<Employee, 'birthday'> & { birthday: Date }

export type AddEmployeesResquest = Omit<Employee, 'id'>

export interface AddEmployeesResponse {
  success: boolean;
  data: string;
}